### ISSUE TITLE
how to use sedumi?

### ISSUE THREAD

**Issue by zmkm1402022** [sqlp/sedumi#10]
hi,

I read the paper of "Parameterized modeling of multiport passive circuit blocks", and I am trying to model a six port transformer. Since I am new in the modeling field, and don't quite understand the full details of sedumi. 
Can you explain how to setup the inputs by using sedumi, if I want to solve sum((|real(H(i))-real(H(jwi)|)^2)+sum((|img(H(i))-img(H(jwi)|)^2) with four constraints as you described in SECTION IV of this paper?

Thank you very much for your time.

**Comment by siko1056** [comment]
Sorry for the late reply.  If still of any interest, SeDuMi can be used as solver for the modeling toolboxes:

- [YALMIP](https://yalmip.github.io/examples/)
- [CVX](http://cvxr.com/cvx/)

which seem to be of greater value for defining your problem.
