### ISSUE TITLE
fault occurs

### ISSUE THREAD

**Issue by zmkm1402022** [sqlp/sedumi#11]
Hi,
I am running sedumi with a simple example. but it failed as below, do you have any suggestion to solve this issue? Thanks

> > c=[1;-1;0;0];
> > A=[10,-7,-1,0;1,0.5,0,1];
> > b=[5;3];
> > sedumi(A,b,c)
> > SeDuMi 1.3 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
> > Alg = 2: xz-corrector, Adaptive Step-Differentiation, theta = 0.250, beta = 0.500
> > eqs m = 2, order n = 5, dim = 5, blocks = 1
> > nnz(A) = 6 + 0, nnz(ADA) = 4, nnz(L) = 3
> >  it :     b_y       gap    delta  rate   t/tP_  t/tD\*   feas cg cg  prec
> >   0 :            6.02E+000 0.000

---

```
         Assertion detected at Fri Aug 22 19:44:49 2014
```

---

Assertion failed: mxGetM(X_IN) == lenud && mxGetN(X_IN) == 1, at line 123 of file "givensrot.c".
x size mismatch

Configuration:
  MATLAB Version:   7.10.0.499 (R2010a)
  MATLAB License:   161051
  Operating System: Microsoft Windows XP
  Window System:    Version 5.1 (Build 2600: Service Pack 3)
  Processor ID:     x86 Family 6 Model 10 Stepping 9, GenuineIntel
  Virtual Machine:  Java 1.6.0_12-b04 with Sun Microsystems Inc. Java HotSpot(TM) Client VM mixed mode
  Default Encoding:  GBK

Fault Count: 1

Stack Trace:
  [0] mcr.dll:_mnSignalHandler(0xffffffff, 0, 0, 0x7a139d60) + 362 bytes
  [1] mcr.dll:void __cdecl ThrowAssertion(void)(0, 0x00c2dde4, 0x65737341, 0x6f697472) + 156 bytes
  [2] mcr.dll:_MATLABAssertFcn(0x671850fc ": mxGetM(X_IN) == lenud && mxGet..", 0x6718504d "givensrot.c", 123, 0x671850e9 "x size mismatch") + 121 bytes
  [3] libut.dll:_ut_assertstr(0x671850fc ": mxGetM(X_IN) == lenud && mxGet..", 0x6718504d "givensrot.c", 123, 0x671850e9 "x size mismatch") + 26 bytes

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/ts/help_request_1.html

A technical support engineer might contact you with further information.

Thank you for your help. We recommend that you save your workspace and restart MATLAB as soon as possible.

Caught MathWorks::System::FatalException

**Comment by siko1056** [comment]
Maybe no longer of interest.  But using both Octave and Matlab on a Linux PC, I cannot reproduce your error

```
>> c=[1;-1;0;0];
>> A=[10,-7,-1,0;1,0.5,0,1];
>> b=[5;3];
>> sedumi(A,b,c)
SeDuMi 1.32 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, Adaptive Step-Differentiation, theta = 0.250, beta = 0.500
eqs m = 2, order n = 5, dim = 5, blocks = 1
nnz(A) = 6 + 0, nnz(ADA) = 4, nnz(L) = 3
 it :     b*y       gap    delta  rate   t/tP*  t/tD*   feas cg cg  prec
  0 :            6.02E+00 0.000
  1 :  -1.20E+00 1.84E+00 0.000 0.3055 0.9000 0.9000   1.86  1  1  2.1E+00
  2 :  -6.94E-02 5.15E-01 0.000 0.2803 0.9000 0.9000   2.14  1  1  8.6E-01
  3 :  -1.21E-01 2.72E-02 0.000 0.0528 0.9900 0.9900   1.16  1  1  4.2E-02
  4 :  -1.25E-01 8.69E-06 0.000 0.0003 0.9999 0.9999   1.02  1  1  
iter seconds digits       c*x               b*y
  4      0.2  14.7 -1.2500000000e-01 -1.2500000000e-01
|Ax-b| =   6.6e-16, [Ay-c]_+ =   0.0E+00, |x|=  2.9e+00, |y|=  2.8e-01

Detailed timing (sec)
   Pre          IPM          Post
1.873E-01    2.041E-01    2.120E-02    
Max-norms: ||b||=5, ||c|| = 1,
Cholesky |add|=0, |skip| = 0, ||L.L|| = 1.

ans =

   (1,1)       1.9583
   (2,1)       2.0833
```

If your error is still present, this report can be reopened.
