### ISSUE TITLE
f77blas.h not found (Ubuntu, Octave)

### ISSUE THREAD

**Issue by catch22** [sqlp/sedumi#17]
The fix I found was to install `libopenblas-dev` and replace the include statement in `blksdp.h` to `#include <openblas/f77blas.h>` (cf. 44fe8cc4593795c0dfab45eb0d613b28e6a317eb).

**Comment by nvitucci** [comment]
Since there are many files having the same problem, I found it easier to add a flag `-I/usr/include/openblas` in the `install_sedumi.m` script (in the `need_rebuild/ISOCTAVE` section). 

This worked on Fedora, but I am not sure about other systems (hence why I am not 100% sure this is PR-worthy). What do you think?

**Comment by siko1056** [comment]
https://github.com/sqlp/sedumi/blob/d559b73e08a1c535404d5c0ce9150ac2fd3d475c/blksdp.h#L40-L47

`f77blas.h` is a pure OpenBLAS header.  If you are using a different BLAS/LAPACK implementation, SeDuMi is not likely to work with Octave today.  Unfortunately, Octave does not distribute the BLAS/LAPACK function prototypes in the `blas.h` header, like Matlab does. Octave currently only exposes a subset of these function in the C++ headers [`lo-blas-proto.h`](https://hg.savannah.gnu.org/hgweb/octave/file/7f5008aec7a1/liboctave/numeric/lo-blas-proto.h) and [`lo-lapack-proto.h`](https://hg.savannah.gnu.org/hgweb/octave/file/7f5008aec7a1/liboctave/numeric/lo-lapack-proto.h) that cannot be included for compilation with mex (only C). This made the change 44fe8cc necessary, as many Octave users use OpenBLAS anyway.

The change proposed by @catch22 would break the current Octave 5.1.0 Windows installations.  The header `f77blas.h` is deployed in the `C:\Octave\Octave-5.1.0.0\mingw64\include` directory.

The change proposed by @nvitucci is not the cleanest solution to hardcode a directory, but it might cover several default configured GNU/Linux distributions.

You can provide a PR @nvitucci and if there are no different opinions, it is likely to get merged.

**Comment by nvitucci** [comment]
Thanks @siko1056 , will do. I think we can add this as a parameter in the install script, so that the exact location will not be hardcoded.

**Comment by nvitucci** [comment]
@siko1056 Done on https://github.com/sqlp/sedumi/pull/49.

**Comment by catch22** [comment]
The harcoded directory does not seem to work with Ubuntu. See the error log at https://travis-ci.org/catch22/quantbox/builds/641260667#L968 and the travis config at https://github.com/catch22/quantbox/blob/master/.travis.yml. Please let me know if you need any further information.

**Comment by siko1056** [comment]
Do you rely for current software development on Ubuntu (14.04 LTS) "Trusty Tahr", [which ran out of standard support last year](https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions) and [OpenBLAS 0.2.8 from 2013](https://github.com/xianyi/OpenBLAS/tree/v0.2.8)?

https://github.com/catch22/quantbox/blob/4c07cb8090996ecdee8c0b69aecc7c8e9750ea3f/.travis.yml#L2

My impression is, that the OpenBLAS headers were not install in Ubuntu 14.04 https://launchpad.net/ubuntu/trusty/amd64/libopenblas-dev/0.2.8-6ubuntu1

Can you verify this on an Ubuntu 14.04 machine running with "libopenblas-dev" installed, what is the output of

```
find /usr -iname "f77blas.h"
```

You can easily upgrade your Travis CI check to a more recent Ubuntu (16.04 LTS) "Xenial Xerus" for which this path will work (as for almost any other current Linux distribution).

https://packages.ubuntu.com/xenial/amd64/libopenblas-dev/filelist

**Comment by catch22** [comment]
Yikes, great catch. Thanks!

**Comment by siko1056** [comment]
Welcome, thanks for using this repo and reporting issues.  Can this item be closed again?

https://travis-ci.org/catch22/quantbox/builds/641277190#L990

Off-topic: "quantbox" looks interesting to me :wink:
