### ISSUE TITLE
Typo in eigK.m

### ISSUE THREAD

**Issue by cgd8d** [sqlp/sedumi#18]
At https://github.com/sqlp/sedumi/blob/6c49c13e4fcb76e426c3f9b229d17c1088062caa/eigK.m#L77, replace line 77:

```
li(li+1:li+nl) = x(xi+1:xi+nl);
```

with

```
lab(li+1:li+nl) = x(xi+1:xi+nl);
```

**Comment by siko1056** [comment]
Thank you @cgd8d for your suggestion and sorry for the five years without reply.  Your change has now been fixed with b7deadd5dc05354ca739849434da59cce6231bb1 in #54 .
