### ISSUE TITLE
error in Sedumi run in matlab 2014

### ISSUE THREAD

**Issue by pedramhajipour** [sqlp/sedumi#20]
hello
I run sedumi 3.1 in MATLAB 2014 
bur dosen't work

> > Untitled

---

SeDuMi installation script
 Directory: C:\Users\Hagipoor\Desktop
##  Matlab 8.3.0.532 (R2014a) on PCWIN64

Looking for existing binaries...none found; building...
Attempting to recompile the SeDuMi binaries:
Template: mex -O -largeArrayDims <sources> -L"E:\Program Files\MATLAB\R2014a\extern\lib\win64\microsoft" -lmwblas
 bwblkslv.mexw64: bwblkslv.c sdmauxFill.c sdmauxRdot.c
 choltmpsiz.mexw64: choltmpsiz.c
 cholsplit.mexw64: cholsplit.c
 dpr1fact.mexw64: dpr1fact.c auxfwdpr1.c sdmauxCone.c sdmauxCmp.c sdmauxFill.c sdmauxScalarmul.c sdmauxRdot.c blkaux.c
 symfctmex.mexw64: symfctmex.c symfct.c
 ordmmdmex.mexw64: ordmmdmex.c ordmmd.c
 quadadd.mexw64: quadadd.c
 sqrtinv.mexw64: sqrtinv.c sdmauxCone.c
 givensrot.mexw64: givensrot.c auxgivens.c sdmauxCone.c
 urotorder.mexw64: urotorder.c auxgivens.c sdmauxCone.c sdmauxTriu.c sdmauxRdot.c
 psdframeit.mexw64: psdframeit.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c
 psdinvjmul.mexw64: psdinvjmul.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c blkaux.c
 bwdpr1.mexw64: bwdpr1.c sdmauxCone.c sdmauxRdot.c
 fwdpr1.mexw64: fwdpr1.c auxfwdpr1.c sdmauxCone.c sdmauxScalarmul.c
 fwblkslv.mexw64: fwblkslv.c sdmauxScalarmul.c
 qblkmul.mexw64: qblkmul.c sdmauxScalarmul.c
 blkchol.mexw64: blkchol.c blkchol2.c sdmauxFill.c sdmauxScalarmul.c
 vecsym.mexw64: vecsym.c sdmauxCone.c
 qrK.mexw64: qrK.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c
 finsymbden.mexw64: finsymbden.c sdmauxCmp.c
 symbfwblk.mexw64: symbfwblk.c
 whichcpx.mexw64: whichcpx.c sdmauxCone.c
 ddot.mexw64: ddot.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c
 makereal.mexw64: makereal.c sdmauxCone.c sdmauxCmp.c
 partitA.mexw64: partitA.c sdmauxCmp.c
 getada1.mexw64: getada1.c sdmauxFill.c
 getada2.mexw64: getada2.c sdmauxCone.c sdmauxRdot.c sdmauxFill.c
 getada3.mexw64: getada3.c spscale.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c sdmauxCmp.c
 adendotd.mexw64: adendotd.c sdmauxCone.c
 adenscale.mexw64: adenscale.c
 extractA.mexw64: extractA.c
 vectril.mexw64: vectril.c sdmauxCone.c sdmauxCmp.c
 qreshape.mexw64: qreshape.c sdmauxCone.c sdmauxCmp.c
 sortnnz.mexw64: sortnnz.c sdmauxCmp.c
 iswnbr.mexw64: iswnbr.c
 incorder.mexw64: incorder.c
 findblks.mexw64: findblks.c sdmauxCone.c sdmauxCmp.c
 invcholfac.mexw64: invcholfac.c triuaux.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c blkaux.c
## At least one compilation failure occurred.

SeDuMi was not successfully installed.

**Comment by johanlofberg** [comment]
Why don't you use the binaries which already are compiled for your setup.

**Comment by pedramhajipour** [comment]
please send me a correct file for rinning

**Comment by johanlofberg** [comment]
??

You download it from here

**Comment by pedramhajipour** [comment]
where site ??

**Comment by johanlofberg** [comment]
https://github.com/sqlp/sedumi

green download link

**Comment by pedramhajipour** [comment]
thank you
is this file compatible with matlab 2014b ?

**Comment by pedramhajipour** [comment]
i think sedumi is a function that we must run before any SDP  program
which file is main code for rinning

**Comment by johanlofberg** [comment]
Download the whole package. In there, you have all the files necessary. You call sedumi.m (but I recommend you to use an interface, such as YALMIP or CVX)

**Comment by pedramhajipour** [comment]
hello  dear lofberg
i have problem when run a example
please attach file

**Comment by johanlofberg** [comment]
What problem?

https://github.com/sqlp/sedumi/archive/master.zip

**Comment by pedramhajipour** [comment]
error in using sedumi finction
after run sefumi in matlab2014

**Comment by pedramhajipour** [comment]
i run a simple  problem about using sedumi
i attach sample with my gmail and sent you
please see it and error in command window

**Comment by pedramhajipour** [comment]
HELLO
i run a example  with
b=[1 4]';
A=[-1 1 0 1 1;0 0 -1 1 2];
c=[0 2 0 3.5 6]';
[x, y, info] = sedumi(A,b,c);
 unfortunately
i have problem to solve:
[x, y, info] = sedumi(A,b,c);
SeDuMi 1.32 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, Adaptive Step-Differentiation, theta = 0.250, beta =
0.500
eqs m = 2, order n = 6, dim = 6, blocks = 1
nnz(A) = 7 + 0, nnz(ADA) = 4, nnz(L) = 3
 it :     b*y       gap    delta  rate   t/tP*  t/tD*   feas cg cg  prec
  0 :            4.58E+01 0.000
Error using maxstep
Too many input arguments.

Error in wregion (line 99)
        maxt1 = min(maxstep(dx,xc,uxc,K), maxstep(dz,zc,uzc,K));

Error in sedumi (line 477)
    [xscl,yNxt,zscl,y0Nxt, w,relt, dxmdz,err, wr] = ...

**Comment by johanlofberg** [comment]
You've either missed to setup the path completely, or you have somehow managed to put the path to sedumi before the definition of the path to the dsp toolbox. The file maxstep is currently found in the wrong directory

sedumi has to be on top here
```
>> which maxstep -all
C:\Local Homes\johlo46\sedumi\maxstep.m
C:\Program Files\MATLAB\R2013b\toolbox\dsp\filterdesign\@adaptfilt\maxstep.m  % adaptfilt method
C:\Program Files\MATLAB\R2013b\toolbox\dsp\dsp\maxstep.m                      % Shadowed 
```

**Comment by pedramhajipour** [comment]
thank you very much
that's great
i solve it :)
>> install_sedumi

---------------------------------------------------------------------------
SeDuMi installation script
   Directory: C:\Users\Hagipoor\Desktop\pedram
   Matlab 8.3.0.532 (R2014a) on PCWIN64
---------------------------------------------------------------------------
Looking for existing binaries...found!
   If for some reason you need to rebuild the binaries, use this command:
      install_sedumi -rebuild
---------------------------------------------------------------------------
Adding SeDuMi to the Matlab path:
   Base directory...added.
   Conversion directory...added.
   Examples directory...added.
Please save the Matlab path if you want to use SeDuMi from any directory.
---------------------------------------------------------------------------
SeDuMi has been succesfully installed.
For more information, type "help sedumi" or see the user guide.
---------------------------------------------------------------------------

>> exam1
SeDuMi 1.32 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, Adaptive Step-Differentiation, theta = 0.250, beta =
0.500
eqs m = 2, order n = 6, dim = 6, blocks = 1
nnz(A) = 7 + 0, nnz(ADA) = 4, nnz(L) = 3
 it :     b*y       gap    delta  rate   t/tP*  t/tD*   feas cg cg  prec
  0 :            4.58E+01 0.000
  1 :   8.27E+00 1.37E+01 0.000 0.2992 0.9000 0.9000   1.99  1  1  1.3E+00
  2 :   1.15E+01 3.16E+00 0.000 0.2304 0.9000 0.9000   1.81  1  1  2.4E-01
  3 :   1.19E+01 5.77E-01 0.000 0.1826 0.9000 0.9000   1.19  1  1  4.1E-02
  4 :   1.20E+01 2.97E-03 0.000 0.0051 0.9990 0.9990   1.01  1  1
iter seconds digits       c*x               b*y
  4      0.2  15.8  1.2000000000e+01  1.2000000000e+01
|Ax-b| =   8.8e-16, [Ay-c]_+ =   8.6E-20, |x|=  2.2e+00, |y|=  3.0e+00

Detailed timing (sec)
   Pre          IPM          Post
1.570E-01    2.400E-01    4.899E-02
Max-norms: ||b||=4, ||c|| = 6,
Cholesky |add|=0, |skip| = 0, ||L.L|| = 1.80888.

x =

   (1,1)       1.0000
   (5,1)       2.0000


y =

   -0.0000
    3.0000


info =

         iter: 4
    feasratio: 1
         pinf: 0
         dinf: 0
       numerr: 0
           r0: 1.7657e-16
       timing: [0.1570 0.2400 0.0490]
      wallsec: 0.4460
       cpusec: 0.4368

>>
