### ISSUE TITLE
error when installing sedumi in matlab2016b

### ISSUE THREAD

**Issue by cdhit2010** [sqlp/sedumi#22]
install_sedumi
Building SeDuMi binaries...
mex  -O -DPC -DmwIndex=int -DmwSize=int -DmwSignedIndex=int bwblkslv.c sdmauxFill.c sdmauxRdot.c "D:\Program Files\MATLAB\R2016b\extern\lib\win64\microsoft\libmwlapack.lib"
使用 'Microsoft Visual C++ 2015 Professional (C)' 编译。
错误使用 mex
bwblkslv.c
d:\program files\matlab\r2016b\extern\include\tmwtypes.h(791): error C2632: “int”后面的“int”非法
d:\program files\matlab\r2016b\extern\include\tmwtypes.h(791): warning C4091: “typedef ”: 没有声明变量时忽略“int”的左侧
d:\program files\matlab\r2016b\extern\include\tmwtypes.h(792): error C2632: “int”后面的“int”非法
d:\program files\matlab\r2016b\extern\include\tmwtypes.h(792): warning C4091: “typedef ”: 没有声明变量时忽略“int”的左侧
d:\program files\matlab\r2016b\extern\include\tmwtypes.h(793): error C2632: “int”后面的“int”非法
d:\program files\matlab\r2016b\extern\include\tmwtypes.h(793): warning C4091: “typedef ”: 没有声明变量时忽略“int”的左侧
F:\Matlab-Program\SeDuMi_1_3\bwblkslv.c(184): warning C4028: 形参 1 与声明不同
F:\Matlab-Program\SeDuMi_1_3\bwblkslv.c(184): warning C4028: 形参 3 与声明不同
F:\Matlab-Program\SeDuMi_1_3\bwblkslv.c(204): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
F:\Matlab-Program\SeDuMi_1_3\bwblkslv.c(215): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
F:\Matlab-Program\SeDuMi_1_3\bwblkslv.c(224): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
F:\Matlab-Program\SeDuMi_1_3\bwblkslv.c(257): warning C4244: “=”: 从“const double”转换到“int”，可能丢失数据
F:\Matlab-Program\SeDuMi_1_3\bwblkslv.c(259): warning C4244: “=”: 从“const double”转换到“int”，可能丢失数据

出错 install_sedumi (line 113)
    eval( temp );

**Comment by johanlofberg** [comment]
First: why are you trying to recompile the binaries? The shipped binaries work in MATLAB 2016b Win64 without issues.

**Comment by cdhit2010** [comment]
I read the readme.txt. It said to install the sedumi. so I run the function"install_sedumi".
But now I found that It doesn't need install. Is it true that I should do nothing before use the tool.

**Comment by johanlofberg** [comment]
Most likely you don't have to do anything except setting your path. readme should be updated

**Comment by cdhit2010** [comment]
OK, thank you very much!
