### ISSUE TITLE
Sedumi and Octave 4.2

### ISSUE THREAD

**Issue by roon63** [sqlp/sedumi#24]
When trying to use any example from examples  directory I get following error:
sedumi(At,b,c,K)
error: whichcpx: Assertion failed: nlhs <= 1, at line 154 of file "whichcpx.c".
whichcpx generates 1 output argument.

I think that building did not pass correctly.

**Comment by siko1056** [comment]
For a possible explanation and fix see https://savannah.gnu.org/bugs/index.php?50050 . It does not seem to be an issue of SeDuMi. I faced the same issue and now all examples work for me again.

**Comment by siko1056** [comment]
Upstream Octave bug was fixed in 2017 and should no longer be a problem with newer versions of Octave.
