### ISSUE TITLE
MEX files not compatible with R2017a

### ISSUE THREAD

**Issue by mcg1969** [sqlp/sedumi#25]
I'm finding that CVX's mex files, which include SeDuMI and SDPT3, are incompatible with MATLAB R2017a. This is quite unfortunate ;-( it is not clear to me if we can recompile them in a manner which is compatible with pre-R2017a versions as well, and if not, we'd have to make sure we can host both binaries somehow.

**Comment by siko1056** [comment]
Matlab R2017a seems to be an exception. Which system did you actually use (Win, macOS, Linux)?
 
Those mex files worked for me with several previous Matlab versions.  Recently I tested with R2019b (MS Windows) and R2019a (Linux).

I am closing this report, as it is not the latest Matlab release any longer, but we can reopen it any time.
