### ISSUE TITLE
SeDuMi installed unsuccessfully on MATLAB 2017a

### ISSUE THREAD

**Issue by CHZFTW92** [sqlp/sedumi#26]
This is part of what i get after running the install_sedumi.m

SeDuMi installation script
   Directory: /Applications/MATLAB_R2017a.app/toolbox/sedumi-master
   Matlab 9.2.0.556344 (R2017a) on MACI64
---------------------------------------------------------------------------
Attempting to recompile the SeDuMi binaries:
Template: mex -O -largeArrayDims <sources> -lmwblas
   bwblkslv.mexmaci64: bwblkslv.c sdmauxFill.c sdmauxRdot.c
Building with 'Xcode with Clang'.
/Applications/MATLAB_R2017a.app/toolbox/sedumi-master/sdmauxRdot.c:47:12: warning: implicit declaration of function 'ddot__' is invalid in C99 [-Wimplicit-function-declaration]
    return FORT(ddot)(&nn,(double*)x,&one,(double*)y,&one);
           ^
/Applications/MATLAB_R2017a.app/toolbox/sedumi-master/blksdp.h:45:17: note: expanded from macro 'FORT'
#define FORT(x) FORTRAN_WRAPPER(x)
                ^
/Applications/MATLAB_R2017a.app/extern/include/blas.h:24:28: note: expanded from macro 'FORTRAN_WRAPPER'
#define FORTRAN_WRAPPER(x) x ## _
                           ^
<scratch space>:464:1: note: expanded from here
ddot__
^
1 warning generated.

**Comment by siko1056** [comment]
As your compiler tells you:

`FORT(ddot)` gets expanded to `ddot__` with two underscores. That is wrong and should result in `ddot_` with a single underscore.

Can you try to fix `sedumi-master/sdmauxRdot.c` in lines 47 and 57 using:

    return ddot_(&nn ....

instead of `return FORT(ddot)(&nn ...`

**Comment by mkr3mer** [comment]
I tried compiling using MATLAB R2017a on OSX. I found that /Applications/MATLAB_R2017a.app/extern/include/blas.h already defines 'ddot' as 'FORTRAN_WRAPPER(ddot)' which is why there are two underscores instead of one.

**Comment by emammendes** [comment]
Dear mkr3mer and CHZFTW92 

I am having the same problem not only with the file pointed in a previous email but several other files.  Have you found a way to successfully compile sedumi under 2007a-mac?  

Many thanks

Ed

**Comment by mkr3mer** [comment]
I compiled SeDuMi for R2017a by modifiying blksdp.h as follows:

-#define FORT(x) FORTRAN_WRAPPER(x)
+#define FORT(x) x

**Comment by emammendes** [comment]
Many thanks.   After compiling sedumi with the suggested mofication, sedumi(1,1,1) returned

>> sedumi(1,1,1)
SeDuMi 1.32 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, Adaptive Step-Differentiation, theta = 0.250, beta = 0.500
eqs m = 1, order n = 2, dim = 2, blocks = 1
nnz(A) = 1 + 0, nnz(ADA) = 1, nnz(L) = 1
 it :     b*y       gap    delta  rate   t/tP*  t/tD*   feas cg cg  prec
  0 :            8.00E+00 0.000
  1 :   7.87E-01 5.00E-01 0.000 0.0625 0.9900 0.9900   1.40  1  1  2.9E-01
  2 :   1.00E+00 1.65E-04 0.000 0.0003 0.9999 0.9999   1.09  1  1  
iter seconds digits       c*x               b*y
  2      0.3   Inf  1.0000000000e+00  1.0000000000e+00
|Ax-b| =   0.0e+00, [Ay-c]_+ =   0.0E+00, |x|=  1.0e+00, |y|=  1.0e+00

Detailed timing (sec)
   Pre          IPM          Post
2.956E-02    3.202E-01    7.749E-02    
Max-norms: ||b||=1, ||c|| = 1,
Cholesky |add|=0, |skip| = 0, ||L.L|| = 1.

ans =

     1

**Comment by jtcook2** [comment]
I have tried MATLAB 2017a and 2016b on a 2016 MacBook Pro and get the following error. It just says there was one compilation failure but not clues about which. 

>> install_sedumi -rebuild

---------------------------------------------------------------------------
SeDuMi installation script
   Directory: /Users/cookjt1/DynamicSystemsSOS/sedumi
   Matlab 9.1.0.441655 (R2016b) on MACI64
---------------------------------------------------------------------------
Attempting to recompile the SeDuMi binaries:
Template: mex -O -largeArrayDims <sources> -lmwblas
   bwblkslv.mexmaci64: bwblkslv.c sdmauxFill.c sdmauxRdot.c
   choltmpsiz.mexmaci64: choltmpsiz.c
   cholsplit.mexmaci64: cholsplit.c
   dpr1fact.mexmaci64: dpr1fact.c auxfwdpr1.c sdmauxCone.c  sdmauxCmp.c sdmauxFill.c sdmauxScalarmul.c sdmauxRdot.c blkaux.c
   symfctmex.mexmaci64: symfctmex.c symfct.c
   ordmmdmex.mexmaci64: ordmmdmex.c ordmmd.c
   quadadd.mexmaci64: quadadd.c
   sqrtinv.mexmaci64: sqrtinv.c sdmauxCone.c
   givensrot.mexmaci64: givensrot.c auxgivens.c sdmauxCone.c
   urotorder.mexmaci64: urotorder.c auxgivens.c sdmauxCone.c sdmauxTriu.c sdmauxRdot.c
   psdframeit.mexmaci64: psdframeit.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c
   psdinvjmul.mexmaci64: psdinvjmul.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c blkaux.c
   bwdpr1.mexmaci64: bwdpr1.c sdmauxCone.c sdmauxRdot.c
   fwdpr1.mexmaci64: fwdpr1.c auxfwdpr1.c sdmauxCone.c sdmauxScalarmul.c
   fwblkslv.mexmaci64: fwblkslv.c sdmauxScalarmul.c
   qblkmul.mexmaci64: qblkmul.c sdmauxScalarmul.c
   blkchol.mexmaci64: blkchol.c blkchol2.c sdmauxFill.c sdmauxScalarmul.c
   vecsym.mexmaci64: vecsym.c sdmauxCone.c
   qrK.mexmaci64: qrK.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c
   finsymbden.mexmaci64: finsymbden.c sdmauxCmp.c
   symbfwblk.mexmaci64: symbfwblk.c
   whichcpx.mexmaci64: whichcpx.c sdmauxCone.c
   ddot.mexmaci64: ddot.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c
   makereal.mexmaci64: makereal.c sdmauxCone.c sdmauxCmp.c
   partitA.mexmaci64: partitA.c sdmauxCmp.c
   getada1.mexmaci64: getada1.c sdmauxFill.c
   getada2.mexmaci64: getada2.c sdmauxCone.c sdmauxRdot.c sdmauxFill.c
   getada3.mexmaci64: getada3.c spscale.c sdmauxCone.c sdmauxRdot.c sdmauxScalarmul.c sdmauxCmp.c
   adendotd.mexmaci64: adendotd.c sdmauxCone.c
   adenscale.mexmaci64: adenscale.c
   extractA.mexmaci64: extractA.c
   vectril.mexmaci64: vectril.c sdmauxCone.c sdmauxCmp.c
   qreshape.mexmaci64: qreshape.c sdmauxCone.c sdmauxCmp.c
   sortnnz.mexmaci64: sortnnz.c sdmauxCmp.c
   iswnbr.mexmaci64: iswnbr.c
   incorder.mexmaci64: incorder.c
   findblks.mexmaci64: findblks.c sdmauxCone.c sdmauxCmp.c
   invcholfac.mexmaci64: invcholfac.c triuaux.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c blkaux.c
At least one compilation failure occurred.
---------------------------------------------------------------------------
SeDuMi was not successfully installed.
Please attempt to correct the errors and try again.
---------------------------------------------------------------------------

**Comment by emammendes** [comment]
Hi

Have you modified blksdp.h as required?

Cheers

Ed

**Comment by jtcook2** [comment]
I must have missed a posting about this. Is there a link? The instructions just seem to say to run install_sedumi.m in the the README. Thanks for the help.

**Comment by jtcook2** [comment]
Hi Ed,

https://groups.google.com/forum/#!topic/yalmip/K6UF4UFVo9Y

Found the link for the fix.

-#define FORT(x) FORTRAN_WRAPPER(x)
+#define FORT(x) x

at line at line 45 in blksdp.h

**Comment by emammendes** [comment]
Great!

Did it work?

**Comment by jtcook2** [comment]
Sure did! Thanks!

**Comment by davidromerot** [comment]
Just a note. I was able to use the pre-compiled MEX files that are currently in the repository without compiling anything.
**You may not need to run install_sedumi**. Try first just using the MEX files there (at least the mexa64 files), e.g., by adding the folder where you put the clone of the repository to your Matlab path. It worked for me on Matlab2017 running on Ubuntu 16.04.
