### ISSUE TITLE
Remove mex files from repository?

### ISSUE THREAD

**Issue by echu** [sqlp/sedumi#3]
Is it possible to have a clean repository without all the mex binaries? (Or does it require a bunch of dependencies to build?)

Just having a Makefile or a matlab script that calls "mex" would probably be a better long-term solution for the sanity of the repository.

**Comment by siko1056** [comment]
After several years, I think to close this issue.  The present old mex files did a great job for many years and systems.  To avoid breaking working stuff, we should just keep them.

Currently I ensure that newer versions of Matlab and Octave can build own versions of the mex files without trouble.
