### ISSUE TITLE
Sedumi installed successfully but not being called properly MATLAB R2017a

### ISSUE THREAD

**Issue by wagnerdr** [sqlp/sedumi#31]
Greetings, 

I have currently installed successfully the latest version of Sedumi (commit  702f40b) installed on MATLAB r2017a on the following MacBook system 

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB

with MacOS High Sierra 10.13.3 (17D102). 

I am using Sedumi with YALMIP and Gloptipoly 3.

Using both yalmiptest('sedumi') and the gloptipoly3demo I get a similar issue that starts whenever sedumi gets called: 

For YALMIP ----

 
Testing function testsdpvar
 
 
Testing function feasiblelp
 
 
SeDuMi had unexplained problems, maybe due to linear dependence?
YALMIP tweaks the problem (adds 1e6 magnitude bounds on all variables) and restarts...

"SeDuMi had unexplained problems, maybe due to linear dependence?
YALMIP tweaks the problem (adds 1e6 magnitude bounds on all variables) and restarts..."

For Gloptipoly ----

See attached file. Output is too large for including here.

MOSEK runs fine with my current build and has been tested using both YALMIP and Gloptipoly. 

As for the output running install_sedumi ----

---------------------------------------------------------------------------
SeDuMi installation script
   Directory: /Users/wagnerdr/Documents/MATLAB/sedumi
   Matlab 9.2.0.538062 (R2017a) on MACI64
---------------------------------------------------------------------------
Looking for existing binaries...found!
   If for some reason you need to rebuild the binaries, use this command:
      install_sedumi -rebuild
---------------------------------------------------------------------------
Adding SeDuMi to the Matlab path:
   Base directory...already there.
   Conversion directory...already there.
   Examples directory...already there.
---------------------------------------------------------------------------
SeDuMi has been succesfully installed.
For more information, type "help sedumi" or see the user guide.
---------------------------------------------------------------------------

I'm kind of at a loss on this one. Could someone please help me? 

- Dan 

[Missing symbol '__Block_release' required by.txt](https://github.com/sqlp/sedumi/files/1825053/Missing.symbol.__Block_release.required.by.txt)

**Comment by siko1056** [comment]
Can you call SeDuMi directly without errors?

```Matlab
cd /dir/to/sedumi
install_sedumi
load('examples/arch0.mat')
[x,y,info] = sedumi(At,b,c,K);
```

Did you really make sure to use the mex files provided by this repository?  Maybe download it again.

Sometimes I face your error on Linux+Octave, when the binaries are linked against the wrong libraries.  This will not work in Matlab, if you cannot properly compile mex files there!

To rebuild the SeDuMi mex files, first remove all previous mex- and object-files:

```
rm *.mex* *.o
```

Then, from within the Octave or Matlab command window, rebuild the mex files again:

```Matlab
install_sedumi -rebuild
```

**Comment by wagnerdr** [comment]
I followed your suggestions and here was the output from running install_sedumi -rebuild command 

[rebuild.txt](https://github.com/sqlp/sedumi/files/1830736/rebuild.txt)

**Comment by siko1056** [comment]
Did the `-rebuild` it improve the situation?  Means can you run SeDuMi standalone, using YALMIP, etc.?

The warnings of your attached `rebuild.txt` seem related to #26 .

**Comment by siko1056** [comment]
No further comments.
