### ISSUE TITLE
Octave 4.0, install failed

### ISSUE THREAD

**Issue by rickllyxu** [sqlp/sedumi#32]
**Run install_sedumi**:
SeDuMi installation script
   Directory: /home/airplus/sedumi
   Octave 4.0.0 on x86_64-pc-linux-gnu

Looking for existing binaries...none found; building...
Attempting to recompile the SeDuMi binaries:
Template: mex -O -DOCTAVE <sources> -lblas
.....
**At least one compilation failure occurred.

SeDuMi was not successfully installed.
Please attempt to correct the errors and try again.**

And if I run **install_sedumi.m**:
It further alters **error: can't perform indexing operations for <unknown type> type**

Any help is welcome.

**Comment by siko1056** [comment]
Which Linux distribution do you use?  A common problem was, that the compiler `mex` a.k.a. `mkoctfile` is not installed by default, see for example https://packages.debian.org/stretch/liboctave-dev .  If you can properly call `mkoctfile` from the Octave command line, you can rebuild the binaries by running

    install_sedumi -rebuild

**Comment by rickllyxu** [comment]
Thank you! After installing `liboctave-dev` and `install_sedumi -rebuild`, Compilation gets successful.
btw, I copy the file `f77blas.h` and `openblas_config.h` to the sedumi directory, or it will give a not found error.

**Comment by rickllyxu** [comment]
thanks the alternative solution.
