### ISSUE TITLE
Makefile for sedumi using Intel Compiler and gcc

### ISSUE THREAD

**Issue by emammendes** [sqlp/sedumi#33]
Hello

I wrote a Makefile that allows the compilation of sedumi on mac using either icc (intel) or gcc.  In order to do I had to fix some c sources. I wonder whether I could make the makefile (and sedumi)  available on my github account.  I test the new mexmaci64 on a mac running 2017b and it worked fine.  

Many thanks.

Ed

**Comment by siko1056** [comment]
This sounds like an improvement for SeDuMi.  I am not sure how actively this repository is maintained at the moment.

Maybe you can reach a wider audience with your changes by creating a [pull request](https://help.github.com/articles/about-pull-requests/) to this repository, if you can spare the (reasonable) time to create one.

**Comment by johanlofberg** [comment]
Definitely do a pull-request if you can if you think it will help the community.

**Comment by emammendes** [comment]
Many thanks but don't you both want to see what has been done?   I can send the links to my github. If you think it is worth doing a pull-request I will definitely do

**Comment by siko1056** [comment]
No further comments or PRs.
