### ISSUE TITLE
Undefined function or variable 'qrK'

### ISSUE THREAD

**Issue by GDelimpa** [sqlp/sedumi#34]
Hello!
So, I am a new user of Sedumi.
I try to solve a simple SOSP with SOSTOOLS using the Sedumi solver.
I use MATLAB R2018a, running on MAC OS Sierra.

I get the following error:

_Undefined function or variable 'qrK'.

Error in sdinit (line 86)
vfrm.s = qrK(d.u,K);

Error in sedumi (line 401)
[d, v,vfrm, y,y0, R] = sdinit(A,b,c,dense,K,pars);

Error in sossolve (line 149)
	[x,y,info] = sedumi(At,b,c,K,pars);_

**The thing is that qrK.mexa64 and qrK.mexglx actually exist in my directory, so I don't know why MATLAB cannot find it. **

Any help?

**Comment by siko1056** [comment]
Sorry for the late reply.  Is this still an issue for you?
