### ISSUE TITLE
i have problem with sedumi i rebuilt it but it dont work

### ISSUE THREAD

**Issue by macsedumi** [sqlp/sedumi#36]
Invalid MEX-file '/Users/ayk/Downloads/sedumi-master/whichcpx.mexmaci64':
dlopen(/Users/.../Downloads/sedumi-master/whichcpx.mexmaci64, 6): Library not loaded: @loader_path/libmwlapack.dylib
 Referenced from: /Users/.../Downloads/sedumi-master/whichcpx.mexmaci64
 Reason: image not found.

**Comment by svenpopping** [comment]
The solution to this problem is installing the sedumi solver using the [tbxmanager](http://www.tbxmanager.com/).
