### ISSUE TITLE
using sostool and sedumi on matlab 2018a, but sostool demo8 didn't work, compatibility issue?

### ISSUE THREAD

**Issue by xyz314** [sqlp/sedumi#37]
Hi, 
I am a beginner on sedumi and sostool.  I installed them both on matlab 2018a and ran demo examples and found out that sostool demo8 didn't work correctly.  The following are the error:

Error using psdinvjmul Assertion failed (m>1) at line 290 of file 'reflect.c'... then some stack trace error which I won't post here(not sure how useful that would be), then the following error... Error in wregion (line 98) psdinvjmul(vTAR,vfrm.s,dxmdz, K)];
Error in sedumi (line 478) wregion(L,Lden,Lsd,...
Error in sossolve (line 149) [x,y,info] = sedumi(At,b,c,K,pars);
Error in sosdemo8 (line 44) prog = sossolve(prog,solver_opt);

This is because some of the input variable are null, so the dimension m is 0, causing the crash.  

As this is a demo code, I don't expect something is wrong.  I suspect either I installed sedumi and sostool incorrectly, or there is a compatibility issue.   However, all other demo files in sostool works.  sedumi (1,1,1) also worked as expect.   So I suspect there is a compatibility issue between the three software.  

 If there is a compatibility issue, which matlab version I should use?  Thank you very much in advance!

Since this could be compatibility issue between three softwares, I know it might not be the compatibility issue between sedumi and matlab 2018a, I am just trying to get as much information as I can. 

Thank you!

**Comment by siko1056** [comment]
Which examples of the [SOSTOOLS](https://www.cds.caltech.edu/sostools/) did you run, and what was the resolution of this issue (maybe a link or a short description)?  This might be helpful for others struggling with the same problem one day.
