### ISSUE TITLE
Is SeDuMi 1.32 the latest version?

### ISSUE THREAD

**Issue by nicolagrillanda** [sqlp/sedumi#38]
Dear Sirs, 
I installed today SeDuMi version 1.32 but I wonder if this is the latest version or not.
I read about a SeDuMi 1.34, but I have not found it anywhere. May I kindly ask you if 1.32 is the most recent version?
Thank you in advance.
Best regards,
Nicola

**Comment by siko1056** [comment]
Dear Nicola,

The version policy of this repository is not 100% consistent.  It does not make use of the GitHub release feature, thus the information is widespread in the files and not necessarily updated:

https://github.com/sqlp/sedumi/blob/702f40b17cd1d72580c87cdd1e553fb96e2b7b9e/Readme.txt#L1
https://github.com/sqlp/sedumi/blob/702f40b17cd1d72580c87cdd1e553fb96e2b7b9e/Changelog.txt#L80
https://github.com/sqlp/sedumi/blob/702f40b17cd1d72580c87cdd1e553fb96e2b7b9e/Version.txt#L1
https://github.com/sqlp/sedumi/blob/702f40b17cd1d72580c87cdd1e553fb96e2b7b9e/sedumi.m#L310
https://github.com/sqlp/sedumi/blob/702f40b17cd1d72580c87cdd1e553fb96e2b7b9e/install_sedumi.m#L5

Nevertheless, I really appreciate the work of the contributors of this repository.  It works out of the box for me for years!  Personally, I would label this version 1.32 and think that this is the "most maintained" version of SeDuMi in contrast to the official page: http://sedumi.ie.lehigh.edu/

If you really need to be sure about a unique version, you might use the git commit id
702f40b17cd1d72580c87cdd1e553fb96e2b7b9e as reference.

Kind regards,
Kai
