### ISSUE TITLE
SET has been considered obsolete

### ISSUE THREAD

**Issue by Josiran1** [sqlp/sedumi#39]
Dear Joahn
please help me with this problem

Warning: Strict inequalities are not supported. A non-strict has been added instead') 
> In  >  (line 12)
  In implementacao (line 31) 
SET has been considered obsolete for many years, and the time has come...
Update your code. http://users.isy.liu.se/johanl/yalmip/pmwiki.php?n=Commands.set
Error using constraint/set (line 6)
Obsolete command

Error in implementacao (line 31)
LMIs=LMIs+set(P>0)+set([X sqrt(R)*Y; Y'*sqrt(R) P]>0);
------------------------------------------------------------------------------------------------------------- 

this code
% SIMULAÇÃO DO PROCESSO DE 2a ORDEM MIMO DO TANQUE
% DADO AS SEGUINTES MATRIZES DE EQUAÇÃO DE ESTADOS

r1=[0.15 0.25]; r2=[0.2 0.3]; c1=5; c2=c1;

% OBTENDO AS INCERTEZAS DO PROCESSO
for i=1:2
for j=1:2
a{2*(i-1)+j}=[-r1(i)/c1 r1(i)/c1; r1(i)/c2 -((r1(i)/c2)+(r2(j)/c2))];
end
end
b(1,1)=1/c1; b(2,2)=1/c2; b(1,2)=0; b(2,1)=0; c=eye(2); d=zeros(2);

% APLICAÇÃO DO CONTROLE LQR-LMI NAS INCERTEZAS
for i=1:4
ahat{i}=[a{i} zeros(size(b)); -c zeros(size(d))];
end
bhat=[b; zeros(size(d))];

% PARAMETROS DAS MATRIZES DE PONDERAÇÃO
R=100*[1 0;0 1]; Q=[1 0 0 0;0 1 0 0;0 0 0.1 0;0 0 0 0.1];

% % gerando matrizes simetricas
LMIs=set([]);
X=sdpvar(2,2,'symmetric');
Y=sdpvar(2,4,'full');
P=sdpvar(4,4,'symmetric');
for i=1:4
LMIs=LMIs+set(P>0)+set([X sqrt(R)*Y; Y'*sqrt(R) P]>0);
LMIs=LMIs+set(ahat{i}*P+P*ahat{i}'-bhat*Y-Y'*bhat'+eye(4)<0);
end
obj=trace(Q*P)+trace(X);
sol=solvesdp(LMIs,obj);
khat=double(Y)*inv(double(P));
k=khat(1:2,1:2); ki=-khat(1:2,3:end);
r1=mean([0.15 0.25]); r2=mean([0.2 0.3]); c1=5; c2=5;
aa=[-r1/c1 r1/c1; r1/c2 -((r1/c2)+(r2/c2))];
A=[aa-b*k b*ki; -c zeros(size(d))];
B=[zeros(size(b)); eye(size(d))];
C=[c zeros(size(d))];
D=d;
x0=zeros(4,1); t=0:1:400; nit=length(t);
r=[0.2*ones(1,ceil(nit/2)) 0.15*ones(1,ceil(nit/2)-1);
0.1*ones(1,ceil(nit/2)) 0.15*ones(1,ceil(nit/2)-1)];
sys=ss(aa,b,c,d);
sysc=ss(A,B,C,D);
[y,t,x]=lsim(sysc,r,t,x0);
y=y+(1+2*rand)*1e-3*randn(size(y));
x=x+(1+2*rand)*1e-3*randn(size(x));
u=(-khat*x')';

% Respostas no tempo
figure(1),subplot(2,1,1), plot(t,r(1,:)','k-.',t,y(:,1),'k-','linewidth',2), axis([0 nit-1 0 0.25]),
set(gca,'fontsize',10,'fontname','Times New Roman')
xlabel('Tempo(s)','fontsize',12,'fontname','Times NewRoman','fontangle','normal'),
ylabel('Altura h_1 (m)','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
legend('ref','saida h_1'); grid
title('ALTURAS DO TANQUE','fontsize',12,'fontname','Times NewRoman','fontangle','normal')

subplot(2,1,2), plot(t,r(2,:)','k-.',t,y(:,2),'k-','linewidth',2),
axis([0 nit-1 0 0.25]),
set(gca,'fontsize',10,'fontname','Times New Roman')
xlabel('Tempo(s)','fontsize',12,'fontname','Times NewRoman','fontangle','normal'),
ylabel('Altura h_2 (m)','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
legend('ref','saida h_2'); grid

figure(2),
subplot(2,1,1), plot(t,u(:,1),'k-','linewidth',2), axis([0 nit-1 -0.01
0.05]), grid
set(gca,'fontsize',10,'fontname','Times New Roman')
xlabel('Tempo(s)','fontsize',12,'fontname','Times NewRoman','fontangle','normal'),
ylabel('q_1 (m^3/s)','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
title('VAZÕES DO TANQUE','fontsize',12,'fontname','Times NewRoman','fontangle','normal')

subplot(2,1,2), plot(t,u(:,2),'k-','linewidth',2), axis([0 nit-1 -0.01 0.05]), gridset(gca,'fontsize',10,'fontname','Times New Roman')
xlabel('Tempo(s)','fontsize',12,'fontname','Times NewRoman','fontangle','normal'),ylabel('q_2 (m^3/s)','fontsize',12,'fontname','Times NewRoman','fontangle','normal')

% Respostas na Frequencia
% Obtenção das incertezas na frequência
sys4=ss(double(a{4}),b,c,d); T4=sys4; S4=eye(2)-T4;
sys3=ss(double(a{3}),b,c,d); T3=sys3; S3=eye(2)-T3;
sys2=ss(double(a{2}),b,c,d); T2=sys2; S2=eye(2)-T2;
sys1=ss(double(a{1}),b,c,d); T1=sys1; S1=eye(2)-T1;
sys_ma=ss(aa,b,c,d);
T=sysc; %sensibilidade complementar
S=eye(2)-T; %sensibilidade
w=logspace(-3,2,200); %faixa de frequencia
M1=(sys1/sys_ma)-eye(2);
M2=(sys2/sys_ma)-eye(2);
M3=(sys3/sys_ma)-eye(2);
M4=(sys4/sys_ma)-eye(2);
s=tf('s');
Dm1=M1.c*inv(s*M1.e-M1.a)*M1.b+M1.d;
Dm2=M2.c*inv(s*M2.e-M2.a)*M2.b+M2.d;
Dm3=M3.c*inv(s*M3.e-M3.a)*M3.b+M3.d;
Dm4=M4.c*inv(s*M4.e-M4.a)*M4.b+M4.d;

figure(3),
sigma(T,'k-',T1,'k--',T2,'k--',T3,'k--',T4,'k--');
set(gca,'fontsize',10,'fontname','Times New Roman')
xlabel('Frequência','fontsize',12,'fontname','Times NewRoman','fontangle','normal'),
ylabel('Amplitude','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
title('SVD Aplicado à T(s)','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
legend('MTMF', 'MTMA');
grid;

figure(4),
sigma(S,'k-',S1,'k--',S2,'k--',S3,'k--',S4,'k--');
set(gca,'fontsize',10,'fontname','Times New Roman')
xlabel('Frequência','fontsize',12,'fontname','Times NewRoman','fontangle','normal'),
ylabel('Amplitude','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
title('SVD Aplicado à S','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
legend('MTMF', 'MTMA');
title('SVD Aplicado a S(s)');
grid

figure(5),
sigma(T/S,'k-',T1/S1,'k--',T2/S2,'k--',T3/S3,'k--',T4/S4,'k--');
set(gca,'fontsize',10,'fontname','Times New Roman')
xlabel('Frequência','fontsize',12,'fontname','Times NewRoman','fontangle','normal'),
ylabel('Amplitude','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
title('SVD Aplicado à S','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
legend('|GK|', 'G_i');
title('SVD Aplicado ao modelo controlado em MTMA');
grid

figure(6),
sigma(1/T,'k-',M1,'k--',M2,'k--',M3,'k--',M4,'k--');
set(gca,'fontsize',10,'fontname','Times New Roman')
xlabel('Frequência','fontsize',12,'fontname','Times NewRoman','fontangle','normal'),
ylabel('Amplitude','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
title('SVD Aplicado à S','fontsize',12,'fontname','Times NewRoman','fontangle','normal')
legend('1/T', 'M(j\omega)');
title('Analise de Estabilidade Robusta');
grid

**Comment by johanlofberg** [comment]
https://yalmip.github.io/tutorial/basics/

**Comment by johanlofberg** [comment]
and this is a YALMIP question and compltely unrelted to sedumi.
