### ISSUE TITLE
Where to download SeDuMi verison 1.05?

### ISSUE THREAD

**Issue by DiJinTUD** [sqlp/sedumi#44]
Hi, I am wondering whether we can find the SeDuMi version 1.05? Thanks.

**Comment by siko1056** [comment]
To my knowledge there is not such an official download location for this particular version anymore.  The official download page http://sedumi.ie.lehigh.edu/ does only offer a version 1.3.

The only chance to get this particular version is that maybe someone has a stale copy in his backups.  Some Google search pointed me to a [public Brazilian FTP server](http://ftp.feq.ufu.br/Luis_Claudio/HYBRID/mpt_ver262/mpt/solvers/) probably ownded by [Luís Cláudio Oliveira Lopes](http://www.ppgeq.feq.ufu.br/pessoas/docentes/luis-claudio-oliveira-lopes) hosting a folder called "SeDuMi105".  This folder indeed looks by using a diff-tool with the current version like the desired version 1.05.

For my interest and your convenience, I downloaded that folder [SeDuMi105.zip](https://github.com/sqlp/sedumi/files/3400799/SeDuMi105.zip).

**But please don't treat this file as something valid or official.** It is obtained from some unofficial source...
