### ISSUE TITLE
open if statement in prelp.m

### ISSUE THREAD

**Issue by mkarikom** [sqlp/sedumi#46]
This appears to be a bug:

    if ~exist('loadata','file') || ~exist('preprocess','file')
    if ~exist('loadata','file') | ~exist('preprocess','file')
        error('To use PRELP, you need to have LIPSOL installed.')
    end

removing the second if fixes compilation errors in mcc

**Comment by siko1056** [comment]
Confirmed.  I found another duplicate which just does the work of loading data twice.  Both are fixed with pr #48.
