### ISSUE TITLE
Bug installing Sedumi on matlab

### ISSUE THREAD

**Issue by ach4l** [sqlp/sedumi#5]
I tried installing Sedumi in Matlab 2009b.

I get the error : Building SeDuMi binaries...
mex  -O -DPC bwblkslv.c sdmauxFill.c sdmauxRdot.c "C:\Program Files (x86)\MATLAB\R2009b\extern\lib\win32\microsoft\libmwblas.lib"
Writing library for bwblkslv.mexw32 
c:\users\agrawal\appdata\local\temp\mex_of~1\sdmauxrdot.obj .text: undefined reference to '_ddot' 

  C:\PROGRA~2\MATLAB\R2009B\BIN\MEX.PL: Error: Link of 'bwblkslv.mexw32' failed. 

??? Error using ==> mex at 221
Unable to complete successfully.

Error in ==> install_sedumi at 114
    eval( temp );

I saw another person with the same problem. did anyone encounter similar problems and has a solution?

Any help would be greatly appreciated.

**Comment by Aminos01** [comment]
Hi,
  I have a problem with sedumi package, I don't understand why it doesn't work. When I compilate the file " install_sedumi" it displays the following message :   


// >> install_sedumi
Building SeDuMi binaries...
Mex file entry point is missing.  Please check the (case-sensitive) 
spelling of mexFunction (for C MEX-files), or the (case-insensitive) 
spelling of MEXFUNCTION (for FORTRAN MEX-files).
Invalid MEX-file 'C:\Windows\system32\version.dll': Le
module spécifié est introuvable.

Error in install_sedumi (line 80)
version1  = sscanf(version,'%d.%d');    //

would you please tell me qhat can I do to solve the problem 
thank you in advance for your help

**Comment by mcg1969** [comment]
You wouldn't be chance be using a very old version of MATLAB, would you? I don't understand, frankly, why it is even *trying* to recompile the binaries. The package we've built here includes MEX files for Windows, Linux, and Mac.

**Comment by Aminos01** [comment]
Thanks mcg1969,
I am using the latest version of Matlab "R2013a"  !!

**Comment by KRICHEL01** [comment]
I try again with others versions of matlab "R2014b" and "R2013b", and it still display me an error message :  
" Unable to complete successfully.

Error in install_sedumi (line 113)
    eval( temp ); "

Someone have a suggestion for me,
thanks in advance for your help

**Comment by mcg1969** [comment]
Well, again, it's not clear to me why the install script is even *trying* to recompile the binaries in either of your cases. My suggestion to you is to run the debugger through the install_sedumi script and try and figure out why it is deciding to do so.

**Comment by mcg1969** [comment]
From the comments to `install_sedumi`:
```
%
% We don't want to rebuild the binaries if they're already present, unless
% the user has specifically asked for a rebuild. Frankly, we can't
% guarantee that rebuilding will work.
%
```
Again, neither of you should be recompiling the binaries. You should either just skip `install_sedumi` altogether and manually add SeDuMi to your path, or debug the script to figure out why it thinks you *need* to recompile them.
