### ISSUE TITLE
Why unexplained crash in SeDuMi?

### ISSUE THREAD

**Issue by musabbir1** [sqlp/sedumi#50]
My sedumi on MAC says 
"Nope, unexplained crash in SeDuMi! (could be memory issues or wrong binary)
Make sure you have a recent and compiled version"

**Comment by siko1056** [comment]
Maybe macOS did a breaking change with the recent updates.  The attached set of binaries is not that new 1e0844d4f1f227c07e1a21efc71b9401b5095b27 ("Compile with R2012b on Snow Leopard").

If you have a [supported compiler with your Matlab on your Mac](https://www.mathworks.com/support/requirements/supported-compilers.html) to call `mex`, change inside Matlab to the SeDuMi directory and run

```
install_sedumi -rebuild
load('examples/arch0.mat');
[x,y,info] = sedumi(At,b,c,K);
```

To recompile the binaries again and verify that SeDuMi is working with them.
