### ISSUE TITLE
Octave 5.1 flatpak installation errors

### ISSUE THREAD

**Issue by teerav42** [sqlp/sedumi#51]
Full disclosure, I don't really know what I'm doing.

I had SeDuMi working fine in Octave 4.4.1 on Ubuntu. Then I installed Octave version 5.1.0. Then when I tried to use SeDuMi, I got error messages like

```
error: pretransfo: /path/to/sedumi/whichcpx.mex: failed to load: liboctinterp.so.6: cannot open shared object file: No such file or directory
error: called from
    pretransfo at line 211 column 5
    sedumi at line 261 column 26
```

I don't really know what this means, but I think it means that I need to recompile the mex files in Octave 5.1.0. I attempted to do this with

`install_sedumi('-rebuild')`

but this resulted in many error messages.

For what it's worth, it appears a new version of Octave, 6.1.0, is [right around the corner](https://lists.gnu.org/archive/html/octave-maintainers/2019-12/msg00032.html). Not sure if or how that will affect things.

**Comment by siko1056** [comment]
> Full disclosure, I don't really know what I'm doing.

No problem.  We'll find out.  For me this GitHub version of SeDuMi runs fine on openSUSE 15.1, Octave 5.1.0 and Octave 6.0.0 (HG_ID:  [797be8d10c22](https://hg.savannah.gnu.org/hgweb/octave/rev/797be8d10c22)).

It would be helpful, if you answered the questions below:

1. How did you install Octave 5.1.0 (flatpak, snap,...?) and on which version of Ubuntu?
2. Do you still have the old version of Octave 4.4.1 installed on your system?  If yes, please remove it entirely.

       sudo apt-get remove octave liboctave-dev

3. In some Ubuntu terminal, can you tell me the output of

       octave    --version
       mkoctfile --version

I suspect you compile the SeDuMi-*.mex files with an older version of `mkoctfile` a.k.a. `mex` which links to an outdated Octave 4.4.1 library version.

**Comment by teerav42** [comment]
I am on Ubuntu 19.10 (technically Xubuntu 19.10, but I doubt that will make a difference). Octave 4.4.1 is what ships with Ubuntu 19.10. I installed Octave 5.1.0 via flatpak.

Here is the requested output from my command line:

```
$ octave --version
GNU Octave, version 4.4.1
Copyright (C) 2018 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.

$ mkoctfile --version
mkoctfile, version 4.4.1
```

However, if I open an Octave 5.1.0 terminal, I get

```
octave:1> mkoctfile --version
mkoctfile, version 5.1.0
```

To summarize, I can compile the SeDuMi-\*.mex files in Octave 4.4.1, but not in Octave 5.1.0. If I compile in Octave 4.4.1, the binaries obtained do not work for Octave 5.1.0. Even if I uninstall Octave 4.4.1, I still cannot compile the SeDuMi-\*.mex files in Octave 5.1.0 (I uninstalled with `sudo apt purge octave liboctave-dev`).

**Comment by siko1056** [comment]
Your file [octave510_attempt_to_compile_mex_files.txt](https://github.com/sqlp/sedumi/files/3996872/octave510_attempt_to_compile_mex_files.txt) reveals the true problem:

```
ld: cannot find -lblas
collect2: error: ld returned 1 exit status
```

In your case, the "*.mex" files where build by Octave 4.4.1 and never replaced by those of Octave 5.1.0.  This is indeed SeDuMi's fault, as the usage of "libblas.so" is  hardcoded:

https://github.com/sqlp/sedumi/blob/8a3796fbdafeb778afd22c11f70816b821ee4bfe/install_sedumi.m#L178-L192

Octave 5.1 flatpak does not contain "libblas.so", but "libopenblas.so" instead.  Thus change this line

https://github.com/sqlp/sedumi/blob/8a3796fbdafeb778afd22c11f70816b821ee4bfe/install_sedumi.m#L187

to

```
libs{end+1} = '-lopenblas';
```

And things should work for you.  I come up with a proper fix for SeDuMi after Xmas.

**Comment by teerav42** [comment]
Great. I don't completely understand the bug, but the fix works. It's interesting to note that sdpt3 does not have this bug, considering the install scripts for sedumi and sdpt3 are similar in a lot of other ways.

Thank you!
