### ISSUE TITLE
SeDumi 1.3 instalation fail in Octave 4.2.2 - Linux 64bits

### ISSUE THREAD

**Issue by luizmac** [sqlp/sedumi#57]
Hello,

could someone give me some help?

I'm having problems to install SeDumi. I'm working with Linux Mint 19.3 Cinnamon - 64 bits and Octave 4.2.2.

I have successfully installed YALMIP and SDPT3. I got the latest version of YALMIP from here:

https://yalmip.github.io/download/

However SeDumi is not working. 

I have doing the following steps:

1) Add path for Sedumi;

2) Running yalmiptest. Results: Fail

When I run yalmiptest it is able to list the Sedumi solver but it can not use it to solve the tests. The messages are something like this

Testing function complete_2

SeDuMi 1.3.4 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, theta = 0.250, beta = 0.500

SeDuMi had unexplained problems, maybe due to linear dependence?
YALMIP tweaks the problem (adds 1e6 magnitude bounds on all variables) and restarts...

SeDuMi 1.3.4 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, theta = 0.250, beta = 0.500
Nope, unexplained crash in SeDuMi! (could be memory issues or wrong binary)
Make sure you have a recent and compiled version

3) Run install file install_sedumi.m. Results: Fail

I receive the following messages. It is a long list so I'm posting just part of them

>> install_sedumi

---------------------------------------------------------------------------
SeDuMi installation script
   Directory: /home/luiz/YALMIP/sedumi-master
   Octave 4.2.2 on x86_64-pc-linux-gnu
---------------------------------------------------------------------------
Looking for existing binaries...none found; building...
Attempting to recompile the SeDuMi binaries:
Template: mex -O2 -DOCTAVE -I/usr/include/openblas %s
   bwblkslv.mex:   bwblkslv.c sdmauxFill.c sdmauxRdot.c
In file included from bwblkslv.c:45:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   choltmpsiz.mex: choltmpsiz.c
   cholsplit.mex:  cholsplit.c
   dpr1fact.mex:   dpr1fact.c auxfwdpr1.c sdmauxCone.c sdmauxCmp.c sdmauxFill.c sdmauxScalarmul.c sdmauxRdot.c blkaux.c
In file included from dpr1fact.c:52:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   symfctmex.mex:  symfctmex.c symfct.c
   ordmmdmex.mex:  ordmmdmex.c ordmmd.c
   quadadd.mex:    quadadd.c
In file included from quadadd.c:42:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   sqrtinv.mex:    sqrtinv.c sdmauxCone.c
In file included from triuaux.h:37:0,
                 from sqrtinv.c:43:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~

4) Trying to rebuild with install_sedumi -rebuild. Results: Fail

Again the results are the same. Posting just part of the messages.

>> install_sedumi -rebuild

---------------------------------------------------------------------------
SeDuMi installation script
   Directory: /home/luiz/YALMIP/sedumi-master
   Octave 4.2.2 on x86_64-pc-linux-gnu
---------------------------------------------------------------------------
Attempting to recompile the SeDuMi binaries:
Template: mex -O2 -DOCTAVE -I/usr/include/openblas %s
   bwblkslv.mex:   bwblkslv.c sdmauxFill.c sdmauxRdot.c
In file included from bwblkslv.c:45:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   choltmpsiz.mex: choltmpsiz.c
   cholsplit.mex:  cholsplit.c
   dpr1fact.mex:   dpr1fact.c auxfwdpr1.c sdmauxCone.c sdmauxCmp.c sdmauxFill.c sdmauxScalarmul.c sdmauxRdot.c blkaux.c
In file included from dpr1fact.c:52:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   symfctmex.mex:  symfctmex.c symfct.c
   ordmmdmex.mex:  ordmmdmex.c ordmmd.c
   quadadd.mex:    quadadd.c
In file included from quadadd.c:42:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   sqrtinv.mex:    sqrtinv.c sdmauxCone.c
In file included from triuaux.h:37:0,
                 from sqrtinv.c:43:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   givensrot.mex:  givensrot.c auxgivens.c sdmauxCone.c
In file included from givensrot.c:41:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   urotorder.mex:  urotorder.c auxgivens.c sdmauxCone.c sdmauxTriu.c sdmauxRdot.c
In file included from urotorder.c:43:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   psdframeit.mex: psdframeit.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c
In file included from psdframeit.c:40:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   psdinvjmul.mex: psdinvjmul.c reflect.c sdmauxCone.c sdmauxRdot.c sdmauxTriu.c sdmauxScalarmul.c blkaux.c
In file included from psdinvjmul.c:43:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   bwdpr1.mex:     bwdpr1.c sdmauxCone.c sdmauxRdot.c
In file included from bwdpr1.c:45:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.
warning: mkoctfile: building exited with failure status
   fwdpr1.mex:     fwdpr1.c auxfwdpr1.c sdmauxCone.c sdmauxScalarmul.c
In file included from fwdpr1.c:44:0:
blksdp.h:41:10: fatal error: f77blas.h: No such file or directory
 #include "f77blas.h"  /* defines "blasint" data type */
          ^~~~~~~~~~~
compilation terminated.

Observations:

Obs1:
I had successfully installed the liblas and lapack on my computer. I have used the command:

$ sudo apt-get install libblas-dev liblapack-dev^C

Obs2: 
After try to install Sedumi the SDPT3 solver do not work anymore. 

Obs3:

Running sedumi(1,1,1) i receive:

>> sedumi(1,1,1)
SeDuMi 1.3.4 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, Adaptive Step-Differentiation, theta = 0.250, beta = 0.500
error: The SeDuMi binaries for your platform are not installed.
To rectify, run the following commands from the Octave command line:

   cd /home/luiz/YALMIP/sedumi-master
   install_sedumi

For more information, read /home/luiz/YALMIP/sedumi-master/Install.txt.
error: called from
    sedumi_binary_error at line 15 column 1
    partitA at line 40 column 1
    sedumi at line 350 column 8

Could someone help me to make Sedumi run properly?

**Comment by luizmac** [comment]
Problem solved!

I was using an old version of Octave (4.2.2). Linux Mint repositories only gives the old version 4.2.2. The current version 5.2.0 does not present any problem! For Linux mint users get it from https://flathub.org/apps/details/org.octave.Octave.

**Comment by siko1056** [comment]
The problem is, that SeDuMi implicitly requires the OpenBLAS headers `libopenblas-dev` to be installed

https://github.com/sqlp/sedumi/blob/fedd22ad2f0964c921452c903c114058b3bcad8e/install_sedumi.m#L186-L188

See how to install and find them here https://github.com/sqlp/sedumi/issues/17#issuecomment-578053529 .  Probably this would have solved the issue, as from the Flatpak installation I know them to be present.
