### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by 12146** [sqlp/sedumi#60]
Dear, Developer,

i am trying to install the Sedumi 1.3 in Matlab 2014a version and i have the Windows 10.

But when i try to run the install.m file it shows error like this
install_sedumi
Building SeDuMi binaries...
mex  -O -DPC -largeArrayDims bwblkslv.c sdmauxFill.c sdmauxRdot.c "D:\MATLAB\extern\lib\win64\microsoft\libmwlapack.lib" -lmwblas
Error using mex
No supported compiler or SDK was found. For options, visit  http://www.mathworks.com/support/compilers/R2014a/win64.

Error in install_sedumi (line 113)
    eval( temp );

i also installed the Microsoft C visual 2015 but still showing the same error.

Please help me with this

**Comment by siko1056** [comment]
In general you don't have to rebuild the binary mex files yourself. Can you download SeDuMi again and run `install_sedumi` **without** the `-rebuild` option or deleting any files?

**Comment by 12146** [comment]
Yes,let i try
and then again contact you

**Comment by siko1056** [comment]
No further reports by @12146.  Issue seems to be fixed.
