### ISSUE TITLE
sedumi：function handle problem in minpsdeig.m

### ISSUE THREAD

**Issue by crucis0** [sqlp/sedumi#64]
in minpsdeig.m （line 70）

https://github.com/sqlp/sedumi/blob/29963063d25fbfc37eacbfb7f1a61bafd2475fd9/minpsdeig.m#L66-L74

there may be an issue in function eigs（XX，1，，‘SA'......）
matlab warn that XX is not a function handle.

**Comment by siko1056** [comment]
This change was done in 58d78d0498e92d2835edd0e03262db9c0f50bac2, according to the [Matlab documentation](https://www.mathworks.com/help/matlab/ref/eigs.html?s_tid=mwa_osa_a#bu2_q3e-opts) 

> - opts — Options structure
>   Option Field | Description | Name-Value Pair
>   -- | -- | --
>   issym | Symmetry of Afun matrix. | 'IsFunctionSymmetric'

and

> 'IsFunctionSymmetric' — Symmetry of Afun matrix

and

> Afun — Matrix function
> function handle
> Matrix function, specified as a function handle.

Matlabs warning seems justified here.

The function is only used in this calling-order:
```
sedumi
  wregion
    maxstep
      minpsdeig
```
Maybe this is why this issue has not been hit often in the past.  Can you provide a minimal example producing this warning message?

**Comment by siko1056** [comment]
The most simple fix is to just remove the struct from the call.  Again according to the Matlab documentation:

> If A is symmetric, then eigs uses a specialized algorithm for that case. If A is nearly symmetric, then consider using A = (A+A')/2 to make A symmetric before calling eigs. This ensures that eigs calculates real eigenvalues instead of complex ones.

Thus no special care for A is necessary to flag it symmetric.  If there are no other opinions about it (or problems with older versions I am not aware of) I'll fix this in a few days.

**Comment by siko1056** [comment]
No further comments, merged #65 .  Thanks again for your report :+1:
