### ISSUE TITLE
Sedumi: Wregion (Line 98), Wrong ues of psdinvjmul 'reflect.c' line 290 fail (m>1)

### ISSUE THREAD

**Issue by Wogwan** [sqlp/sedumi#66]
Hi Professors and Sedumi team administrators, sincerely appreciate for all your great work about Sedumi.

I am using **Sedumi(latest release)+SmrsoftV12(shown as attached)+Mosek** in Matlab R2019a, win10 x64 system.
[smrsoftV12.zip](https://github.com/sqlp/sedumi/files/6325397/smrsoftV12.zip)

When I am running the SEDUMI to solve the SOSP, .m file shown in the attached file:
[example.zip](https://github.com/sqlp/sedumi/files/6325413/example.zip)

an error shown (for directly reading, I post the error report at the end. Hope no offensive). 
![image](https://user-images.githubusercontent.com/57804285/115032619-1834e900-9efc-11eb-9151-4b3b6339d040.png)

Sorry that I am not familiar with the C++, so that I even have no idea what's wrong with the code. Could you leave a hint for further process if available? Hoping for your reply. Thanks!

Best regards,
WOKI

`Error using psdinvjmul
Assertion failed (m>1) at line 290 of file 'reflect.c'.

Stack trace:
[  0] 0x000000001092b2c3                              bin\win64\libmwfl.dll+00045763 foundation::core::diag::thread_context::unspecified_bool+00000051
[  1] 0x0000000010929288                              bin\win64\libmwfl.dll+00037512 foundation::core::diag::stacktrace_base::capture+00000024
[  2] 0x00000000fc607f93                               bin\win64\libmex.dll+00163731 cppmex_mexUnlock_with_error_check+00075219
[  3] 0x00000000fc6108f9                               bin\win64\libmex.dll+00198905 mexPrintAssertion_800+00001081
[  4] 0x00000000f7272eb0 C:\Users\hjhuang\OneDrive\??\2020CDC\matlab_example\Matlab-5b3e8f0b724b518674c6a58427d191fdcb4677b4
(2)\Matlab-5b3e8f0b724b518674c6a58427d191fdcb4677b4\Controlltheory_Robusttheory\sedumi-master\psdinvjmul.mexw64+00011952 mexFunction+00004512
[  5] 0x00000000f72716e1 C:\Users\hjhuang\OneDrive\??\2020CDC\matlab_example\Matlab-5b3e8f0b724b518674c6a58427d191fdcb4677b4
(2)\Matlab-5b3e8f0b724b518674c6a58427d191fdcb4677b4\Controlltheory_Robusttheory\sedumi-master\psdinvjmul.mexw64+00005857
[  6] 0x00000000f7272072 C:\Users\hjhuang\OneDrive\??\2020CDC\matlab_example\Matlab-5b3e8f0b724b518674c6a58427d191fdcb4677b4
(2)\Matlab-5b3e8f0b724b518674c6a58427d191fdcb4677b4\Controlltheory_Robusttheory\sedumi-master\psdinvjmul.mexw64+00008306 mexFunction+00000866
[  7] 0x00000000fc634844                               bin\win64\libmex.dll+00346180 MexRetrieveVersion+00003348
[  8] 0x00000000fc634a3c                               bin\win64\libmex.dll+00346684 MexRetrieveVersion+00003852
[  9] 0x00000000fc634ba4                               bin\win64\libmex.dll+00347044 MexRetrieveVersion+00004212
[ 10] 0x00000000fc618089                               bin\win64\libmex.dll+00229513 mexUnlock+00024825
[ 11] 0x0000000017299a66                     bin\win64\pgo\m_dispatcher.dll+00039526 Mfh_file::dispatch_file_common+00000210
[ 12] 0x000000001732252e                     bin\win64\pgo\m_dispatcher.dll+00599342 Mfh_error::lookup+00005234
[ 13] 0x0000000017322dcd                     bin\win64\pgo\m_dispatcher.dll+00601549 Mfh_file::dispatch+00000045
[ 14] 0x000000001800b7a0                            bin\win64\pgo\m_lxe.dll+00505760
[ 15] 0x000000001800be01                            bin\win64\pgo\m_lxe.dll+00507393
[ 16] 0x00000000180b6ebc                            bin\win64\pgo\m_lxe.dll+01207996
mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree>::load_object_data+00609492
[ 17] 0x00000000180b7ba3                            bin\win64\pgo\m_lxe.dll+01211299
mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree>::load_object_data+00612795
[ 18] 0x00000000180b9ced                            bin\win64\pgo\m_lxe.dll+01219821
mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree>::load_object_data+00621317
[ 19] 0x00000000180b90cf                            bin\win64\pgo\m_lxe.dll+01216719
mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree>::load_object_data+00618215
[ 20] 0x00000000180b95fc                            bin\win64\pgo\m_lxe.dll+01218044
mwboost::archive::detail::iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree>::load_object_data+00619540
[ 21] 0x0000000018009934                            bin\win64\pgo\m_lxe.dll+00497972
[ 22] 0x00000000180102b5                            bin\win64\pgo\m_lxe.dll+00524981
[ 23] 0x000000001800f85c                            bin\win64\pgo\m_lxe.dll+00522332
[ 24] 0x000000001800d9c5                            bin\win64\pgo\m_lxe.dll+00514501
[ 25] 0x000000001800e2b5                            bin\win64\pgo\m_lxe.dll+00516789
[ 26] 0x000000001800dbe5                            bin\win64\pgo\m_lxe.dll+00515045
[ 27] 0x0000000017299a66                     bin\win64\pgo\m_dispatcher.dll+00039526 Mfh_file::dispatch_file_common+00000210
[ 28] 0x000000001732252e                     bin\win64\pgo\m_dispatcher.dll+00599342 Mfh_error::lookup+00005234
[ 29] 0x0000000017322dcd                     bin\win64\pgo\m_dispatcher.dll+00601549 Mfh_file::dispatch+00000045
[ 30] 0x0000000018004fb9                            bin\win64\pgo\m_lxe.dll+00479161
[ 31] 0x00000000181864f2                            bin\win64\pgo\m_lxe.dll+02057458 MathWorks::lxe::StartupLxeEngine+00034326

Error in wregion (line 98)
            psdinvjmul(vTAR,vfrm.s,dxmdz, K)];

Error in sedumi (line 478)
        wregion(L,Lden,Lsd,...

Error in bamiso (line 298)
[x1,x2,x3]=sedumi(datsdmA,datsdmb,datsdmc,datsdmK,pars);

Error in badabest_f_fixv (line 60)
            bamiso

Error in badabest_f (line 2)
    badabest_f_fixv

Error in smrda (line 1999)
    badabest_f

Error in example (line 82)
[bndC,MC,DatC]=smrda(fc,[],v);`

**Comment by Wogwan** [comment]
Thanks for your time. This problem is solved in a simplest way. Thanks!

**Comment by siko1056** [comment]
Would you like to share what caused the error?

**Comment by Wogwan** [comment]
Hi, of course! I have add the SEDUMI files with different locations into the Matlab paths; thus why occured the error before.

What we need to do just follow the error report above, to remove the unnecessary SEDUMI and only keep one in the Matlab paths.

Again, thanks for SEDUMI team.
