### ISSUE TITLE
problem with sedumi installation on mac OS big sur and octave 6.2.0 

### ISSUE THREAD

**Issue by Atrofino** [sqlp/sedumi#69]
Hi, I am receiving the following error message when I try to install sedumi on my macbook with Big Sur OS and Octave 6.2.0.
```
---------------------------------------------------------------------------
SeDuMi installation script
   Directory: /Users/alexandre/lmi-solvers/sedumi-1.3.5
   Octave 6.2.0 on x86_64-apple-darwin18.7.0
---------------------------------------------------------------------------
Looking for existing binaries...none found; building...
Attempting to recompile the SeDuMi binaries:
Template: mex -O2 -DOCTAVE -Wall -I/usr/local/opt/openblas/include %s -L/usr/local/opt/openblas/lib -lopenblas
   bwblkslv.mex:   bwblkslv.c sdmauxFill.c sdmauxRdot.c
In file included from bwblkslv.c:45:
./blksdp.h:41:10: fatal error: 'f77blas.h' file not found
#include "f77blas.h"  /* defines "blasint" data type */
         ^~~~~~~~~~~
1 error generated.
warning: mkoctfile: building exited with failure status
Compilation failed.
error: ---------------------------------------------------------------------------
SeDuMi was not successfully installed.
Please attempt to correct the errors and try again.

For example, try setting the compilation command:

  install_sedumi -rebuild 'mex -O2 -DOCTAVE -Wall -I/usr/local/opt/openblas/include %s -L/usr/local/opt/openblas/lib -lopenblas'
error: called from
    install_sedumi at line 263 column 3
```
I tried the option rebuild but didn't work as well. When I add the sedumi paths I received the message:
```
warning: function /Users/alexandre/lmi-solvers/sedumi-1.3.5/vec.m shadows a built-in function
warning: called from
    /Users/alexandre/.octaverc at line 2 column 3
```
I am not familiar with software installation and I would be thankful with any help to solve this problem.

**Comment by siko1056** [comment]
Thank you for your bug report.  It is important to know how did you install Octave on macOS?

If you are using https://brew.sh (which I can really recommend for Octave and macOS), the missing OpenBLAS dependency should already be installed, see <https://formulae.brew.sh/formula/octave>.

**Comment by Atrofino** [comment]
Hi, thanks for your help. I used the file octave-6.2.0.dmg to install octave. The file was downloaded from https://wiki.octave.org/Octave_for_macOS#cite_note-1
No error message received.

**Comment by siko1056** [comment]
Thanks for the installation info.  Does installing OpenBLAS from brew.sh help?

https://formulae.brew.sh/formula/openblas

**Comment by Atrofino** [comment]
I remove the octave installation (octave-6.2.0) and followed your instructions to reinstall octave 6.3.0 from brew command. The installation was completed with no error.  The final installation commands are below:
----------------------------
==> Installing octave
==> Pouring octave--6.3.0.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/octave/6.3.0: 2,388 files, 56.3MB
alexandre@MacBook-Pro-de-Alexandre ~ % octave
GNU Octave, version 6.3.0
Copyright (C) 2021 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin20.4.0".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.
--------------------------------------------------------------------
 How should I open an octave window? The octave app is no longer available.

**Comment by Atrofino** [comment]
Dear Kai, thanks a lot for your help. Now I have octave 6.3.0, Great! All files are there, including Openblas:
------------------------------------------------------
alexandre@MacBook-Pro-de-Alexandre Cellar % ls
aom			isl			octave
arpack			jasper			open-mpi
cairo			jbig2dec		openblas
docbook			jpeg			openexr
docbook-xsl		libcerf			openjpeg
eigen			libde265		openssl@1.1
epstool			libevent		opus
fftw			libffi			pango
fig2dev			libheif			pcre
flac			libidn			pixman
fltk			liblqr			pkg-config
fontconfig		libmpc			plotutils
freetype		libogg			portaudio
fribidi			libomp			pstoedit
gcc			libpng			pyqt@5
gd			libpthread-stubs	python@3.9
gdbm			libsndfile		qhull
gettext			libtiff			qrupdate
ghostscript		libtool			qscintilla2
gl2ps			libvorbis		qt@5
glib			libx11			readline
glpk			libxau			shared-mime-info
gmp			libxcb			sqlite
gnu-getopt		libxdmcp		suite-sparse
gnuplot			libxext			sundials
gobject-introspection	libxrender		szip
graphicsmagick		little-cms2		tbb
graphite2		lua			texinfo
harfbuzz		lzo			webp
hdf5			m4			x265
hwloc			metis			xmlto
icu4c			mpdecimal		xorgproto
imagemagick		mpfr			xz
imath			netpbm			zstd
alexandre@MacBook-Pro-de-Alexandre Cellar % 
----------------------------------------------------
However octave does not appear in the application list.

**Comment by siko1056** [comment]
With the brew installation, you can start Octave from the Terminal application `octave --gui` <ENTER>.

And to create a convenient application icon, use this short guide: https://wiki.octave.org/Octave_for_macOS#Create_a_launcher_app_with_the_Script_Editor

**Comment by Atrofino** [comment]
Uauuu! Great! Octave, Yalmip and Sedumi are working now. Your help made everything clear and easy, even for a person like me that is not familiar with software installation . Thanks a lot Kai!
The only potential problem is the message below, that I received after setting the sedumi path in octave. Is this a problem?
%%%%%%%%%%

>> warning: function /Users/alexandre/lmi-solvers/sedumi-1.3.5/vec.m shadows a built-in function
warning: function /Users/alexandre/lmi-solvers/sedumi-1.3.5/vec.m shadows a built-in function
warning: savepath: current path saved to ~/.octaverc
warning: function /Users/alexandre/lmi-solvers/sedumi-1.3.5/vec.m shadows a built-in function
warning: savepath: current path saved to ~/.octaverc

%%%%%%%%%% 

Another point concerns  the solver sdpt3. Is this solver available for octave in macOS big sur? I tried to install but I received the message:

>>ls
Citation      GNU_General_Public_License_v2      README                          sdplib
Copyright                       HSDSolver                       Solver                          sdpt3.m
Examples                        Installmex.m                    dimacs                          startup.m

>> Installmex
current directory is:  /Users/alexandre/lmi-solvers/SDPT3-4.0
error: tmp(4): out of bound 0 (dimensions are 0x0)
error: called from
Installmex at line 22 column 18
>>

**Comment by siko1056** [comment]
The warning can be safely ignored.  Overwriting built-in functions is very common to extend the functionality of `vec` to the needs of SeDuMi in this case.

Regarding SDPT3, where did you get your SDPT3 version from?  One version can be obtained from https://github.com/sqlp/sdpt3.  In the `README.md` there, other options are listed.  Maybe you ask where you obtained SDPT3?

**Comment by Atrofino** [comment]
Hi Kai. I downloaded the sdpt3 file from the site https://octave.sourceforge.io/packages.php. But now with your help SDPT3 is installed! Thanks a lot. The last help I would ask you concerns the installation of octave control toolbox that I am downloading from the site https://gnu-octave.github.io/packages/control. Here is the message i receive when I try to install it:
%%
>> pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/control-3.3.1.tar.gz"
sh: gfortran: command not found
sh: gfortran: command not found
make: *** [slicotlibrary.a] Error 127
make: *** Waiting for unfinished jobs....
tar -xzf slicot.tar.gz
/usr/local/Cellar/octave/6.3.0/bin/mkoctfile-6.3.0 -Wall -Wno-deprecated-declarations  __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
if [ "0" = "1" ]; then \
                echo "copy routines using DGGES"; \
                cp SB04OD.fortran ./sltmp/SB04OD.f; \
                cp SG03AD.fortran ./sltmp/SG03AD.f; \
                cp SG03BD.fortran ./sltmp/SG03BD.f; \
        fi;
cp AB08NX.fortran ./sltmp/AB08NX.f
cp AG08BY.fortran ./sltmp/AG08BY.f
cp SB01BY.fortran ./sltmp/SB01BY.f
cp SB01FY.fortran ./sltmp/SB01FY.f
cp SB06ND.fortran ./sltmp/SB06ND.f
cp TB01MD.fortran ./sltmp/TB01MD.f
cp TB01ND.fortran ./sltmp/TB01ND.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cp TG04BX.fortran ./sltmp/TG04BX.f
cp ODLTZM.fortran ./sltmp/ODLTZM.f
cp makefile.slicot ./sltmp/makefile
cd sltmp; /usr/local/Cellar/octave/6.3.0/bin/mkoctfile-6.3.0 -w -c MA02ID.f; rm MA02ID.f; /usr/local/Cellar/octave/6.3.0/bin/mkoctfile-6.3.0 -c *.f;

error: pkg: error running 'make' for the control package.
error: called from
    configure_make at line 110 column 9
    install at line 196 column 7
    pkg at line 568 column 9
>>

%%

**Comment by siko1056** [comment]
With installing the Octave control package we are certainly leaving the realm of SeDuMi :sweat_smile: 

However, as this is the last question, I try to answer it.  For any further Octave (package) questions, please switch to https://octave.discourse.group/ as the right place to get help.  I am very active there too :wink: 

The root of trouble seems to be `sh: gfortran: command not found`.  Can you fix this problem by installing `gcc` via `brew` (again)?

https://formulae.brew.sh/formula/gcc

Unfortunately, when I gave it a try, another issue with macOS, brew and gfortran showed up, that I reported here: https://github.com/Homebrew/discussions/discussions/1986

As the SeDuMi answer is solved, I suggest you wait for the above GitHub discussion to finish, and if installing gfortran (gcc) did not do the trick for you, please reach out for https://octave.discourse.group/.
