### ISSUE TITLE
Octave installation issues 

### ISSUE THREAD

**Issue by Sarita19875437** [sqlp/sedumi#70]
I tried installing all octave versions on My Macbook pro, and all of them are not giving the right one. Any suggestions pls
![IMG_20220306_193250](https://user-images.githubusercontent.com/101300978/157564754-ad4631e2-50df-40bd-a112-49970007e593.jpg)

**Comment by siko1056** [comment]
Thanks for your report.  Could you answer a few questions to help you:
1. How did you install Octave on your MacBook?
2. Where did you download the SeDuMi archive to?  In the screenshot I see you are working in the `/Users` directory.  Can you switch to something like `/Users/Sarita/Downloads` to the extracted `sedumi-1.3.5.zip` or `sedumi-1.3.5.tar.gz` file?

**Comment by Sarita19875437** [comment]
Thank you so much for getting back to me.
I downloaded it from the Octave app once and also tried the one from Octave wiki.
I tried to change the users but it doesn't work. Could you please write to me on my email so I can get more details I really need Octave for my assignment.

**Comment by siko1056** [comment]
For me it is difficult to give more help, as the description of the problem and the performed steps is very vague.  I prefer the conversation here, so other users with the same problem might benefit from it.

Can you explain a little more precise what "I tried to change the users but it doesn't work." means.

Your Octave GUI should look something like this:

![octave screenshot](https://www.gnu.org/software/octave/img/GNU_Octave_4-4-0_screenshot_1600x900.png)

Do you see the extracted SeDuMi folder inside the "File Browser" on the right?  You can navigate inside your file system with the Octave "File Browser" like in the macOS Finder.

**Comment by Sarita19875437** [comment]
I searched SeDuMi in my Finder I Cannot find such a file. Now I uninstalled Octave because it doesn't like anything in the pic you shared. Could you please share with me the steps to install again, I am afraid I have done something wrong, as my Octave looks totally different. Thank you

**Comment by siko1056** [comment]
To install and run Octave on macOS, I recommend using Homebrew:
1. Follow in the [Terminal](https://support.apple.com/en-lk/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac) application the steps from "Install Homebrew" in https://brew.sh/
2. In the Terminal type: `brew install octave` (this might take a while)
3. In the Terminal type: `octave --gui`

Finally from the Octave "command window" run:
```octave
cd ("~/Downloads");
urlwrite ("https://github.com/sqlp/sedumi/archive/refs/tags/v1.3.5.tar.gz", ...
          "sedumi-1.3.5.tar.gz");
gunzip ("sedumi-1.3.5.tar.gz");
cd ("sedumi-1.3.5");
install_sedumi -rebuild;
test_sedumi ();
```
