### ISSUE TITLE
Much slower on Octave than on Matlab

### ISSUE THREAD

**Issue by araujoms** [sqlp/sedumi#72]
I've ran both the Matlab and the Octave versions on a problem I'm working on, and I was surprised to see that the Octave version took about as double the time as the Matlab version. Shouldn't they be equal? After all Matlab/Octave are just doing some preprocessing, and Sedumi does the real work in C.

I've checked the input to Sedumi, and in both cases I get

<pre>Alg = 2: xz-corrector, theta = 0.250, beta = 0.500
eqs m = 24832, order n = 3075, dim = 196616, blocks = 50
nnz(A) = 98484 + 0, nnz(ADA) = 34668544, nnz(L) = 17346688</pre>

So they are indeed solving the same problem, and arrive at exactly the same solution. But on Octave I get 238s of solver time, and on Matlab 177s (this is real solver time, not the one reported by sedumi, as that's incorrect).

I've also tried recompiling the Matlab binaries to see if I was using some poisoned library, but no, the recompilation didn't change the speed.

**Comment by siko1056** [comment]
Thank you for the comparison.  

> After all Matlab/Octave are just doing some preprocessing

To my humble experience, the preprocessing can already be a game changer regarding execution time.  To really pin point specific bottlenecks, it would be great, if you can attach your benchmark example (code and data) to this issue.

Also using profiling https://docs.octave.org/v7.2.0/Profiling.html could provide meaningful insight into what exact code sections make the difference between Octave and Matlab.

**Comment by araujoms** [comment]
I don't think the Octave profiler can help, as it can only time the functions run inside Octave, while in my case the running time is completely dominated by the Sedumi binaries.

I don't want to share my code publicly because it's unpublished research. I can however send you privately if you're interested.

**Comment by araujoms** [comment]
I've ran the profiler, and now I understood the problem: there is a lot of work done in the MATLAB/Octave side of the code, which explains the performance difference.
