### ISSUE TITLE
Problem sdmpb

### ISSUE THREAD

**Issue by Khaye96** [sqlp/sedumi#80]
Good morning,
the sdmp command is not recognized by my Matlab.
I have already installed sedumi, but every time I type the sdmpb command in the script I have this problem.
![Screenshot 2024-01-18 095031](https://github.com/sqlp/sedumi/assets/157036249/368dd2b3-c62c-43ce-bebe-a5e3bd3dbf5a)

How can I solve it?
The operating system is Windows 11, matlab R2021a and sedumi version 1.3.7

**Comment by Khaye96** [comment]
So it can't be used anymore? SeDuMiInterface I say

**Comment by johanlofberg** [comment]
No idea, you would have to install it (if they still have it available) and see

However, why would you. It is a dead project since over 20 years.

**Comment by Khaye96** [comment]
To see the result of that old exercise

However at this point I will start using YALMIP, thanks for the advice
